name: Deploy Terraform

on:
  repository_dispatch:
    types: [deploy]

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        env:
          TF_VAR_scalingo_token: ${{ secrets.SCALINGO_TOKEN }}
        run: terraform apply -auto-approve